apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-result-app
  namespace: erwin-apps
  labels:
    app: vote-result-app
  annotations:
    reloader.stakater.com/auto: "true"
    # secret.reloader.stakater.com/reload: "vote-result-app"
    # configmap.reloader.stakater.com/reload: "vote-result-app"
    # reloader.stakater.com/search: "true"
    # reloader.stakater.com/rollout-strategy: "restart"
spec:
  selector:
    matchLabels:
      app: vote-result-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vote-result-app
    spec:
      imagePullSecrets:
      - name: vote-app-regcred
      containers:
      - name:  vote-result-app
        image:  docker-1.nexus-sa.platform-services-dev.us-east-1.cloudcwt.com/vote-result-app:1.0
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        ports:
        - containerPort: 5001
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_PORT
        - name: PORT
          value: '5001'
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: topology.kubernetes.io/zone
      #           operator: In
      #           values:
      #           - us-east-1a
      #           - us-east-1b
                # - us-east-1c
        # podAntiAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #   - labelSelector:
        #       matchExpressions:
        #       - key: app
        #         operator: In
        #         values:
        #         - vote-result-app
        #     topologyKey: topology.kubernetes.io/zone
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: vote-result
  namespace: erwin-apps
spec:
  # type: NodePort
  selector:
    app: vote-result-app
  ports:
  - port: 5001
    targetPort: 5001
    # nodePort: 30690